spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**







server:
  port: 8084




#Eureka Client Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


