spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
  config:
    import: optional:configserver://config-server

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082

#Eureka Client Configuration
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

