spring:
  application:
    name: RatingService
  mongodb:
    uri: mongodb://localhost:27017/microservices

server:
  port: 8083

#Eureka Client Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

